CREATE TABLE "device_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "device_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"device_id" text NOT NULL,
	"sequence" bigint,
	"level" text NOT NULL,
	"code" text NOT NULL,
	"message" text NOT NULL,
	"boot_id" text,
	"firmware_version" text,
	"hardware_id" text,
	"device_timestamp" bigint,
	"metadata" jsonb,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"gateway_id" text
);
--> statement-breakpoint
CREATE TABLE "device_sync_state" (
	"device_id" text NOT NULL,
	"boot_id" text DEFAULT '' NOT NULL,
	"last_acked_sequence" bigint DEFAULT 0 NOT NULL,
	"last_acked_boot_id" text,
	"last_sync_completed_at" timestamp with time zone,
	"last_overflow_detected_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "device_sync_state_device_id_boot_id_pk" PRIMARY KEY("device_id","boot_id")
);
--> statement-breakpoint
CREATE TABLE "devices" (
	"id" text PRIMARY KEY NOT NULL,
	"last_state" text DEFAULT 'still' NOT NULL,
	"last_seen_at" bigint DEFAULT 0 NOT NULL,
	"last_delta" integer,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"hardware_id" text,
	"boot_id" text,
	"firmware_version" text DEFAULT 'unknown' NOT NULL,
	"machine_label" text,
	"site_id" text,
	"last_gateway_id" text,
	"last_gateway_seen_at" timestamp with time zone,
	"provisioning_state" text DEFAULT 'unassigned' NOT NULL,
	"update_status" text DEFAULT 'idle' NOT NULL,
	"update_target_version" text,
	"update_detail" text,
	"update_reported_at" timestamp with time zone,
	"last_event_received_at" timestamp with time zone,
	"last_heartbeat_at" timestamp with time zone,
	"wifi_provisioned_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "firmware_history_sync_state" (
	"device_id" text PRIMARY KEY NOT NULL,
	"last_acked_history_sequence" bigint DEFAULT 0 NOT NULL,
	"last_history_sync_completed_at" timestamp with time zone,
	"last_history_overflow_detected_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "firmware_releases" (
	"version" text PRIMARY KEY NOT NULL,
	"git_sha" text NOT NULL,
	"asset_url" text NOT NULL,
	"sha256" text NOT NULL,
	"md5" text,
	"size_bytes" bigint NOT NULL,
	"rollout_state" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "motion_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "motion_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"device_id" text NOT NULL,
	"sequence" bigint,
	"state" text NOT NULL,
	"delta" integer,
	"event_timestamp" bigint NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"gateway_id" text,
	"boot_id" text,
	"firmware_version" text,
	"hardware_id" text
);
--> statement-breakpoint
CREATE TABLE "motion_rollups_daily" (
	"device_id" text NOT NULL,
	"bucket_start" bigint NOT NULL,
	"movement_count" integer NOT NULL,
	"moving_seconds" integer NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "motion_rollups_daily_device_id_bucket_start_pk" PRIMARY KEY("device_id","bucket_start")
);
--> statement-breakpoint
CREATE TABLE "motion_rollups_hourly" (
	"device_id" text NOT NULL,
	"bucket_start" bigint NOT NULL,
	"movement_count" integer NOT NULL,
	"moving_seconds" integer NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "motion_rollups_hourly_device_id_bucket_start_pk" PRIMARY KEY("device_id","bucket_start")
);
--> statement-breakpoint
ALTER TABLE "device_sync_state" ADD CONSTRAINT "device_sync_state_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "firmware_history_sync_state" ADD CONSTRAINT "firmware_history_sync_state_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "motion_events" ADD CONSTRAINT "motion_events_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "motion_rollups_daily" ADD CONSTRAINT "motion_rollups_daily_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "motion_rollups_hourly" ADD CONSTRAINT "motion_rollups_hourly_device_id_devices_id_fk" FOREIGN KEY ("device_id") REFERENCES "public"."devices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "device_logs_device_id_idx" ON "device_logs" USING btree ("device_id","received_at");--> statement-breakpoint
CREATE INDEX "device_logs_received_at_idx" ON "device_logs" USING btree ("received_at");--> statement-breakpoint
CREATE INDEX "device_logs_gateway_id_idx" ON "device_logs" USING btree ("gateway_id","received_at");--> statement-breakpoint
CREATE UNIQUE INDEX "device_logs_device_boot_sequence_idx" ON "device_logs" USING btree ("device_id",coalesce("boot_id", ''),"sequence") WHERE "device_logs"."sequence" is not null;--> statement-breakpoint
CREATE INDEX "devices_updated_at_idx" ON "devices" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "devices_site_id_idx" ON "devices" USING btree ("site_id","machine_label");--> statement-breakpoint
CREATE INDEX "devices_last_gateway_id_idx" ON "devices" USING btree ("last_gateway_id","last_gateway_seen_at");--> statement-breakpoint
CREATE INDEX "firmware_releases_rollout_state_idx" ON "firmware_releases" USING btree ("rollout_state","created_at");--> statement-breakpoint
CREATE INDEX "motion_events_device_id_idx" ON "motion_events" USING btree ("device_id","received_at");--> statement-breakpoint
CREATE INDEX "motion_events_device_event_timestamp_idx" ON "motion_events" USING btree ("device_id","event_timestamp");--> statement-breakpoint
CREATE INDEX "motion_events_gateway_id_idx" ON "motion_events" USING btree ("gateway_id","received_at");--> statement-breakpoint
CREATE UNIQUE INDEX "motion_events_device_boot_sequence_idx" ON "motion_events" USING btree ("device_id",coalesce("boot_id", ''),"sequence") WHERE "motion_events"."sequence" is not null;--> statement-breakpoint
CREATE INDEX "motion_rollups_daily_bucket_idx" ON "motion_rollups_daily" USING btree ("bucket_start");--> statement-breakpoint
CREATE INDEX "motion_rollups_hourly_bucket_idx" ON "motion_rollups_hourly" USING btree ("bucket_start");